"use client";

import { useEffect, useMemo, useState } from "react";
import { Sparkles, RefreshCw, Check, Copy } from "lucide-react";
import { hashEvidence, SOURCE_META } from "@/lib/types/evidence";

const MARKER_RE = /\[(chart|pt|family|nurse obs|outside RN[^\]]*)\]/gi;

function markerToSource(marker) {
  const m = marker.toLowerCase();
  if (m === "chart") return "chart";
  if (m === "pt") return "patient";
  if (m === "family") return "family";
  if (m === "nurse obs") return "nurse_observation";
  if (m.startsWith("outside rn")) return "outside_clinician";
  return null;
}

function InlineSourcePill({ marker }) {
  const source = markerToSource(marker);
  const meta = source ? SOURCE_META[source] : null;
  if (!meta) return <span>[{marker}]</span>;
  return (
    <span
      className={`mx-0.5 inline-flex items-center rounded-pill px-1.5 py-0 align-middle text-[10px] font-medium ${meta.bg} ${meta.fg}`}
    >
      {marker}
    </span>
  );
}

function renderWithMarkers(text) {
  if (!text) return null;
  const parts = [];
  let last = 0;
  let key = 0;
  let m;
  MARKER_RE.lastIndex = 0;
  while ((m = MARKER_RE.exec(text)) !== null) {
    if (m.index > last) parts.push(text.slice(last, m.index));
    parts.push(<InlineSourcePill key={key++} marker={m[1]} />);
    last = MARKER_RE.lastIndex;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

function buildPlaintext(sbar) {
  return [
    "SITUATION:",
    sbar.situation,
    "",
    "BACKGROUND:",
    sbar.background,
    "",
    "ASSESSMENT:",
    sbar.assessment,
    "",
    "RECOMMENDATION:",
    sbar.recommendation,
    "",
    `Generated by Kairos · v${sbar.version} · ${sbar.generatedAt}`,
  ].join("\n");
}

function Section({ label, children }) {
  return (
    <section className="space-y-2">
      <h3 className="text-[11px] font-semibold uppercase tracking-[0.05em] text-fg-muted">
        {label}
      </h3>
      <div className="text-[14px] leading-relaxed text-fg">{children}</div>
    </section>
  );
}

export default function SBARDraft({
  encounterContext,
  chartContext,
  evidence,
  onSBARGenerated,
}) {
  const [versions, setVersions] = useState([]);
  const [status, setStatus] = useState("idle"); // idle | loading | error
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  const current = versions[versions.length - 1] || null;
  const evidenceCount = evidence?.length || 0;
  const currentEvidenceHash = useMemo(() => hashEvidence(evidence), [evidence]);

  const stale =
    !!current &&
    (current.evidenceCount !== evidenceCount ||
      current.evidenceHash !== currentEvidenceHash);

  useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 2000);
    return () => clearTimeout(t);
  }, [copied]);

  async function generate() {
    setStatus("loading");
    setError(null);
    try {
      const res = await fetch("/api/regenerate-sbar", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chartContext, evidence, encounterContext }),
      });
      const json = await res.json();
      if (!res.ok) {
        setStatus("error");
        setError(json.error ? `${json.error}: ${json.message || ""}` : `HTTP ${res.status}`);
        return;
      }
      const next = { ...json.sbar, version: versions.length + 1 };
      setVersions((v) => [...v, next]);
      setStatus("idle");
      if (onSBARGenerated) onSBARGenerated(next);
    } catch (err) {
      setStatus("error");
      setError(err.message);
    }
  }

  async function copyToClipboard() {
    if (!current) return;
    try {
      await navigator.clipboard.writeText(buildPlaintext(current));
      setCopied(true);
    } catch (err) {
      setError(`Copy failed: ${err.message}`);
      setStatus("error");
    }
  }

  const isLoading = status === "loading";

  return (
    <article className="rounded-card border border-line-faint bg-surface">
      <header className="flex items-start justify-between gap-4 border-b border-line-faint p-5">
        <div className="space-y-1">
          <h2 className="text-[15px] font-medium text-fg">SBAR Draft</h2>
          {current ? (
            <p className="text-[12px] text-fg-faint">
              v{current.version}
              <span className="mx-1.5 text-fg-faint/60">·</span>
              evidence hash <span className="font-mono">{current.evidenceHash}</span>
              <span className="mx-1.5 text-fg-faint/60">·</span>
              {current.evidenceCount} item{current.evidenceCount === 1 ? "" : "s"}
            </p>
          ) : (
            <p className="text-[12px] text-fg-faint">Not yet generated</p>
          )}
        </div>
        {!current && (
          <button
            type="button"
            onClick={generate}
            disabled={isLoading || evidenceCount === 0}
            title={evidenceCount === 0 ? "Capture at least one piece of evidence first." : undefined}
            className="inline-flex items-center gap-1.5 rounded-button bg-[color:var(--color-accent)] px-3 py-1.5 text-[13px] font-medium text-white transition-colors duration-100 hover:bg-[color:var(--color-accent-hover)] disabled:cursor-not-allowed disabled:opacity-40"
          >
            <Sparkles size={14} strokeWidth={1.75} />
            {isLoading ? "Generating" : "Generate SBAR"}
          </button>
        )}
      </header>

      <div className="p-5">
        {!current && status !== "error" && (
          <p className="text-[13px] text-fg-muted">
            {evidenceCount === 0
              ? "Capture at least one piece of evidence to generate an SBAR draft."
              : `Ready to generate from ${evidenceCount} evidence item${
                  evidenceCount === 1 ? "" : "s"
                }.`}
          </p>
        )}

        {status === "error" && (
          <div className="rounded-button border border-[color:var(--color-flag-high-soft)] bg-[color:var(--color-flag-high-soft)] p-4 text-[13px] text-[color:var(--color-flag-high)]">
            <div className="font-medium">SBAR generation failed</div>
            <div className="mt-1 font-mono text-[12px]">{error}</div>
          </div>
        )}

        {current && (
          <div className="space-y-6">
            {stale && (
              <div className="flex items-start justify-between gap-3 rounded-button border border-[color:var(--color-flag-low-soft)] bg-[color:var(--color-flag-low-soft)] p-3">
                <div className="text-[12px] text-[color:var(--color-flag-low)]">
                  Evidence updated since last generation. Regenerate to incorporate the new items.
                </div>
                <button
                  type="button"
                  onClick={generate}
                  disabled={isLoading}
                  className="inline-flex shrink-0 items-center gap-1.5 rounded-button bg-[color:var(--color-flag-low)] px-2.5 py-1 text-[12px] font-medium text-white transition-opacity duration-100 hover:opacity-90 disabled:opacity-50"
                >
                  <RefreshCw size={12} strokeWidth={1.75} className={isLoading ? "animate-spin" : ""} />
                  Regenerate
                </button>
              </div>
            )}

            <div
              className={`space-y-6 transition-opacity duration-150 ${
                isLoading ? "opacity-50" : ""
              }`}
            >
              <Section label="Situation">{renderWithMarkers(current.situation)}</Section>
              <Section label="Background">{renderWithMarkers(current.background)}</Section>
              <Section label="Assessment">{renderWithMarkers(current.assessment)}</Section>
              <Section label="Recommendation">{renderWithMarkers(current.recommendation)}</Section>
            </div>

            <div className="flex items-center justify-end gap-2 border-t border-line-faint pt-4">
              <button
                type="button"
                onClick={generate}
                disabled={isLoading}
                className="inline-flex items-center gap-1.5 rounded-button px-2.5 py-1.5 text-[13px] font-medium text-[color:var(--color-accent)] transition-colors duration-100 hover:bg-[color:var(--color-accent-soft)] disabled:opacity-50"
              >
                <RefreshCw size={14} strokeWidth={1.75} className={isLoading ? "animate-spin" : ""} />
                Regenerate
              </button>
              <button
                type="button"
                onClick={copyToClipboard}
                className="inline-flex items-center gap-1.5 rounded-button bg-[color:var(--color-accent)] px-3 py-1.5 text-[13px] font-medium text-white transition-colors duration-100 hover:bg-[color:var(--color-accent-hover)]"
              >
                {copied ? (
                  <>
                    <Check size={14} strokeWidth={2} />
                    Copied to clipboard
                  </>
                ) : (
                  <>
                    <Copy size={14} strokeWidth={1.75} />
                    Approve &amp; Copy
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </article>
  );
}
